name: Release plugin

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean package"

      - name: Release
        uses: qcastel/github-actions-maven-release@TAG_NAME
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

